# Generated by Django 4.0.2 on 2022-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(choices=[['2', '2AI'], ['2', '2B'], ['2', '2BI']], max_length=10, null=True),
        ),
    ]
