# Generated by Django 4.0.2 on 2022-09-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
    ]
