# Generated by Django 4.0.2 on 2022-09-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_altu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Altu',
        ),
    ]
