# Generated by Django 4.0.2 on 2022-09-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_delete_altu'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Altu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turma.turma')),
            ],
        ),
    ]
