# Generated by Django 4.0.2 on 2022-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_altu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(choices=[['21', '2AI'], ['22', '2B'], ['23', '2BI']], max_length=10, null=True),
        ),
    ]
