# Generated by Django 4.0.2 on 2022-09-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_alter_turma_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(choices=[['2', '2AI'], ['3', '2B'], ['4', '2BI']], max_length=10, null=True),
        ),
    ]
