# Generated by Django 4.0.2 on 2022-09-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_alter_turma_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
